# Generated by Django 5.2 on 2025-04-12 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="interaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
